lib/whatsforlunch_web/router.ex
defmodule WhatsforlunchWeb.Router do
  use WhatsforlunchWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", WhatsforlunchWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    get "/random", PageController, :random
    get "/random_selection", PageController, :random_selection
    post "/random_range", PageController, :random_range

    resources "/restaurants", RestaurantController

    get "/yelp_search", YelpController, :yelp_search
    post "/yelp_add", YelpController, :yelp_add
  end

  # Other scopes may use custom stacks.
  # scope "/api", WhatsforlunchWeb do
  #   pipe_through :api
  # end
end

lib/whatsforlunch/lunch/restaurant.ex
defmodule Whatsforlunch.Lunch.Restaurant do
  use Ecto.Schema
  import Ecto.Changeset


  schema "restaurants" do
    field :location, :string
    field :name, :string
    field :website, :string

    timestamps()
  end

  @doc false
  def changeset(restaurant, attrs) do
    restaurant
    |> cast(attrs, [:name, :location, :website])
    |> validate_required([:name])
  end
end

lib/whatsforlunch/yelp/restaurant.ex
defmodule Whatsforlunch.Yelp.Restaurant do
    @derive [Poison.Encoder]
    defstruct [:name,:url, :location]
end

lib/whatsforlunch_web/controllers/restaurant_controller.ex
defmodule WhatsforlunchWeb.RestaurantController do
  use WhatsforlunchWeb, :controller

  alias Whatsforlunch.Lunch
  alias Whatsforlunch.Lunch.Restaurant

  require Logger

  def index(conn, _params) do
    restaurants = Lunch.list_restaurants()
    render(conn, "index.html", restaurants: restaurants)
  end

  def new(conn, _params) do
    changeset = Lunch.change_restaurant(%Restaurant{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"restaurant" => restaurant_params}) do
    case Lunch.create_restaurant(restaurant_params) do
      {:ok, restaurant} ->
        conn
        |> put_flash(:info, "Restaurant created successfully.")
        |> redirect(to: restaurant_path(conn, :show, restaurant))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    restaurant = Lunch.get_restaurant!(id)
    render(conn, "show.html", restaurant: restaurant)
  end

  def edit(conn, %{"id" => id}) do
    restaurant = Lunch.get_restaurant!(id)
    changeset = Lunch.change_restaurant(restaurant)
    render(conn, "edit.html", restaurant: restaurant, changeset: changeset)
  end

  def update(conn, %{"id" => id, "restaurant" => restaurant_params}) do
    restaurant = Lunch.get_restaurant!(id)

    case Lunch.update_restaurant(restaurant, restaurant_params) do
      {:ok, restaurant} ->
        conn
        |> put_flash(:info, "Restaurant updated successfully.")
        |> redirect(to: restaurant_path(conn, :show, restaurant))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", restaurant: restaurant, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    restaurant = Lunch.get_restaurant!(id)
    {:ok, _restaurant} = Lunch.delete_restaurant(restaurant)

    conn
    |> put_flash(:info, "Restaurant deleted successfully.")
    |> redirect(to: restaurant_path(conn, :index))
  end
end

lib/whatsforlunch_web/views/restaurant_view.ex
defmodule WhatsforlunchWeb.RestaurantView do
  use WhatsforlunchWeb, :view
end

lib/whatsforlunch_web/templates/restaurant/edit.html.eex
<h2>Edit Restaurant</h2>

<%= render "form.html", Map.put(assigns, :action, restaurant_path(@conn, :update, @restaurant)) %>

<span><%= link "Back", to: restaurant_path(@conn, :index) %></span>

lib/whatsforlunch_web/templates/restaurant/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :location, class: "control-label" %>
    <%= text_input f, :location, class: "form-control" %>
    <%= error_tag f, :location %>
  </div>

  <div class="form-group">
    <%= label f, :website, class: "control-label" %>
    <%= text_input f, :website, class: "form-control" %>
    <%= error_tag f, :website %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/whatsforlunch_web/templates/restaurant/index.html.eex
<h2>Restaurants</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Website</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for restaurant <- @restaurants do %>
    <tr>
      <td><%= restaurant.name %></td>
      <td><%= restaurant.location %></td>
      <td class="word-wrap: break-word">
        <%= if restaurant.website do %>
          <%= if String.starts_with?(restaurant.website, "https://www.yelp.com") do %>
            <a href="<%= restaurant.website %>" target="_blank">Yelp!</a>
          <% else %>
            <a href="<%= restaurant.website %>" target="_blank">Website</a>
          <% end %>
        <% end %>
      </td>
      <%# <td><%= link "Menu", to: restaurant.website </td> %>
      <%# <td><a href="www.google.com"></td> %>
      
      <td class="text-right">
        <span><%= link "Show", to: restaurant_path(@conn, :show, restaurant), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: restaurant_path(@conn, :edit, restaurant), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: restaurant_path(@conn, :delete, restaurant), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Restaurant", to: restaurant_path(@conn, :new) %></span>
<span class="pull-right"><%= link "Search Yelp!", to: yelp_path(@conn, :yelp_search) %></span>

lib/whatsforlunch_web/templates/restaurant/new.html.eex
<h2>New Restaurant</h2>

<%= render "form.html", Map.put(assigns, :action, restaurant_path(@conn, :create)) %>

<span><%= link "Back", to: restaurant_path(@conn, :index) %></span>

lib/whatsforlunch_web/templates/restaurant/show.html.eex
<h2>Show Restaurant</h2>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @restaurant.name %>
  </li>

  <li>
    <strong>Location:</strong>
    <%= @restaurant.location %>
  </li>


  <li>
    <strong>Website:</strong>
    <a href="<%= @restaurant.website %>" target="_blank"><%= @restaurant.website %></a>
  </li>

</ul>

<span><%= link "Edit", to: restaurant_path(@conn, :edit, @restaurant) %></span>
<span><%= link "Back", to: restaurant_path(@conn, :index) %></span>