lib/whatsforlunch_web/router.ex
defmodule WhatsforlunchWeb.Router do
  use WhatsforlunchWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", WhatsforlunchWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    get "/random", PageController, :random
    get "/random_selection", PageController, :random_selection
    post "/random_range", PageController, :random_range

    resources "/restaurants", RestaurantController

    get "/yelp_search", YelpController, :yelp_search
    post "/yelp_add", YelpController, :yelp_add
  end

  # Other scopes may use custom stacks.
  # scope "/api", WhatsforlunchWeb do
  #   pipe_through :api
  # end
end

lib/whatsforlunch_web/views/layout_view.ex
defmodule WhatsforlunchWeb.LayoutView do
  use WhatsforlunchWeb, :view
end

lib/whatsforlunch_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Let's Eat!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-left">
            <span><%= link "Home", to: page_path(@conn, :index) %></span>
          </ul>
          <ul class="nav nav-pills pull-right">
            <span><%= link "Restaurants", to: restaurant_path(@conn, :index) %></span>
          </ul>
        </nav>
        <%# <span class="logo"></span> %>
        <span></span>
      </header>

      </br>
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        </br>
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>